### ISSUE TITLE
Graceful shutdown of gRPC servers when there are exceptions in the User Code

### ISSUE THREAD

**Issue by yhl25** [numaproj/numaflow-java#137]
```[tasklist]
### Tasks
- [x] UD Containers should restart when there are uncaught exceptions in the user code
- [x] JVM doesn't shutdown after the gRPC server is terminated
- [ ] https://github.com/numaproj/numaflow-java/issues/157
```

**Comment by KeranYang** [comment]
@yhl25 , regarding `UDSource health checks fail and sometimes the source will hung in k3d cluster`, yes, I tested that adding 

```
<configuration>
       <from>
             <image>amazoncorretto:11</image>
        </from>
<configuration>

``` 
        
fixed the issue. Plus, it's not only for source but also other UD container types.

**Comment by vigith** [comment]
should we document this?

**Comment by KeranYang** [comment]
> should we document this?

Yes. Once we figured out why we can document. Tracking it here: https://github.com/numaproj/numaflow-java/issues/157

**Comment by KeranYang** [comment]
@vigith added in this PR: https://github.com/numaproj/numaflow-java/pull/158/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
